// Generated by scripts/platform/lib/platform-schema-head-generator.mjs.
// Do not edit by hand.

export const PLATFORM_SCHEMA_CONTRACT_VERSION = 1 as const;

export const platformSchemaHead = {
  tag: "0040_host_grant_consumption",
  createdAt: 1788835707497,
  hash: "446fefda29ca3caeaadef856efb67cf1a501229fec64776137366df79dfa49ba",
  catalogDigest:
    "a17d9ccdc77cfccd42d4d9137d0f01a5c1f6e328277b41c60707290b6579b2a5",
} as const;
