// Generated by scripts/platform/lib/platform-schema-head-generator.mjs.
// Do not edit by hand.

export const PLATFORM_SCHEMA_CONTRACT_VERSION = 1 as const;

export const platformSchemaHead = {
  tag: "0037_superseded_release_retention",
  createdAt: 1788811565297,
  hash: "cc8f848ab77133731a32e43abaa66d763d5dc292aec50505830b940f4a1cb00e",
  catalogDigest:
    "c0a38716861810d7261a710a219a427146692035e59ca94d4041885d45748667",
} as const;
