// Generated by scripts/platform/lib/platform-schema-head-generator.mjs.
// Do not edit by hand.

export const PLATFORM_SCHEMA_CONTRACT_VERSION = 1 as const;

export const platformSchemaHead = {
  tag: "0039_realtime_admission_contract",
  createdAt: 1788835643710,
  hash: "30a3020f1bd73483145cca591e4dfd7c06d42b1b86eb03e79f28eef6c776e22d",
  catalogDigest:
    "1857f4746a6ce83165ee391dd84c5d854a52a913882c18f4e29292fcd8071a09",
} as const;
